### numpy tutorial

In [2]:
#importing numpy
import numpy as np

In [2]:
#creating numpy array
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [3]:
a

array([1, 2, 3, 4])

In [4]:
# creating 2D array
b= np.array([[1,2,3,4],[5,6,7,8]])
print(b)
b

[[1 2 3 4]
 [5 6 7 8]]


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
#get dimension
b.ndim

2

In [7]:
a.ndim

1

In [10]:
#get shape
b.shape

(2, 4)

In [11]:
a.shape

(4,)

In [13]:
#reshape
x =np.array([1,2,3,4,5,6,7,8,9])
print(x)
y = x.reshape(3,3)
print(y)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
#display type
a.dtype

dtype('int32')

In [15]:
b.dtype

dtype('int32')

In [40]:
#returns total number of element
a.itemsize

4

In [17]:
b.itemsize

4

In [20]:
#get total size
a.nbytes

16

In [21]:
#get total number of element
a.size

4

In [22]:
b.size

8

### Accessing and changing specific element,rows and columns

In [31]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [24]:
# get a specific element
a[1,5]

13

In [25]:
#get all element of specific row
a[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [26]:
#get a specific column
a[:,2]

array([ 3, 10])

In [27]:
#[startIndex:endIndex:stepSize]
a[0,1:6:2]

array([2, 4, 6])

In [33]:
#update a specific element
a[1,3] = 25
print(a)
a

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 25 12 13 14]]


array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 25, 12, 13, 14]])

In [35]:
#updating specific column of all row
a[:,2] =89
a

array([[ 1,  2, 89,  4,  5,  6,  7],
       [ 8,  9, 89, 25, 12, 13, 14]])

In [36]:
#updating complete specific row
a[1,:] = 29
a

array([[ 1,  2, 89,  4,  5,  6,  7],
       [29, 29, 29, 29, 29, 29, 29]])

In [37]:
#updating specific column of each row
a[:,2] = [18,19]
print(a)

[[ 1  2 18  4  5  6  7]
 [29 29 19 29 29 29 29]]


### 3-D array

In [41]:
#creating 3-d array

c= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)
c

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [44]:
#accessing element from 3-d array
print(c[0,:,:])

[[1 2]
 [3 4]]


### initializing different types of array

In [47]:
# all 0's  2D array
np.zeros((2,3), dtype ='int32') #default type is double

array([[0, 0, 0],
       [0, 0, 0]])

In [48]:
#all zeros 3-D array
np.zeros((2,3,3), dtype = 'int32')

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [50]:
#all ones 3-D array
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [51]:
# initializing with random value
np.full((2,2),27)

array([[27, 27],
       [27, 27]])

In [52]:
#updating existing array with all it's value to specific value
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [54]:
#random decimal numbers
np.random.rand(4,2)

array([[0.12939536, 0.2706657 ],
       [0.21356389, 0.92420882],
       [0.37962017, 0.81510169],
       [0.45390465, 0.32831214]])

In [55]:
#random integer number with range
np.random.randint(-4,8,size = (3,3))

array([[-2, -2,  5],
       [-4,  4, -3],
       [ 2, -3,  2]])

In [57]:
np.random.randint(-4,12,size = (3,3))

array([[-2,  0, 10],
       [ 0,  4, -2],
       [-1,  7,  2]])

In [60]:
#identity matrix of float
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [4]:
#identity matrix of integer
np.identity(5, dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

### copy and other operation

In [62]:
a= np.array([1,2,3])
b=a
b[0] = 100
print(a)

[100   2   3]


In [64]:
#copy function
a= np.array([1,2,3])
b=a.copy()
b[0]=100
print(b)
print(a)


[100   2   3]
[1 2 3]
