### Arithmatic Operation on numpy array

In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [4]:
b = a+2
print(b)

[3 4 5 6]


In [5]:
a-2

array([-1,  0,  1,  2])

In [6]:
a*2

array([2, 4, 6, 8])

In [7]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [8]:
a%3

array([1, 2, 0, 1], dtype=int32)

In [9]:
a**2

array([ 1,  4,  9, 16])

In [10]:
#adding two array
a= np.array([1,2,3,4])
b= np.array([5,6,7,8])
a+b

array([ 6,  8, 10, 12])

In [11]:
#trignometry function
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [13]:
np.sin(a[2])

0.1411200080598672

### Linear Algebra

In [15]:
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a)
b= np.array([[1,2],[3,4],[5,6],[7,8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [16]:
#matrix multiplication
np.matmul(a,b)

array([[ 50,  60],
       [114, 140]])

In [17]:
#determinant of a matrix
a = np.array([[1,2,3],[7,8,9],[10,11,12]])
np.linalg.det(a)

1.598721155460225e-14

In [18]:
#finding eigen value
np.linalg.eig(a)

EigResult(eigenvalues=array([ 2.22153745e+01, -1.21537451e+00,  1.77757645e-15]), eigenvectors=array([[ 0.1673669 ,  0.82918265,  0.40824829],
       [ 0.5848926 , -0.09125787, -0.81649658],
       [ 0.79365545, -0.55147813,  0.40824829]]))

### Statistics Operation

In [20]:
a= np.array([[3,6,2],[4,5,1]])
a

array([[3, 6, 2],
       [4, 5, 1]])

In [21]:
#finding minimum
np.min(a)

1

In [22]:
#row wise minimum
np.min(a,axis=1)

array([2, 1])

In [23]:
#column wise minimum
np.min(a,0)

array([3, 5, 1])

In [24]:
#finding max
np.max(a)

6

In [28]:
#row-wise max
np.max(a, axis=1)

array([6, 5])

In [29]:
#column-wise max
np.max(a,0)

array([4, 6, 2])

In [30]:
#sum of complete array
np.sum(a)

21

In [31]:
#row-wise sum
np.sum(a,1)

array([11, 10])

In [32]:
#column-wise sum
np.sum(a, axis=0)

array([ 7, 11,  3])

In [33]:
#finding mean
np.mean(a)

3.5

In [34]:
#finding median
np.median(a)

3.5

In [35]:
#standard deviation
np.std(a)

1.707825127659933

In [36]:
#variance
np.var(a)

2.9166666666666665

### Linear Equation 
    # 4X + 5Y = 13
    # 5X - 3Y = 7

In [38]:
coff1 = np.array([[4,5],[5,-3]])
coff2 = np.array([13,7])
np.linalg.solve(coff1,coff2)

array([2., 1.])